name: video_summarization_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - opencv
  - moviepy
  - transformers
  - pytorch
  - numpy
  - pillow
  - reportlab
  - yt-dlp
  - librosa
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - llama-cpp-python
