name: model-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch
      - transformers
      - opencv-python-headless
      - moviepy
      - pillow
      - reportlab
      - yt-dlp
      - google-api-python-client
